services:
  # Database
  database:
    image: mysql:8.0
    container_name: go-react-crawler-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: web-crawler
      MYSQL_USER: web-crawler-user
      MYSQL_PASSWORD: web-crawler-password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot-password",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Go backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-react-crawler-backend
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: web-crawler-user
      DB_PASSWORD: web-crawler-password
      DB_NAME: web-crawler
      JWT_SECRET: 123456
      FRONTEND_ORIGIN: http://localhost:5173
      CHOKIDAR_USEPOLLING: true
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # React frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: go-react-crawler-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://127.0.0.1:8080
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5173",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
